apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cherry-proxy
  name: cherry-proxy
spec:
  selector:
    matchLabels:
      app: cherry-proxy
  replicas: 2
  template:
    metadata:
      labels:
        app: cherry-proxy
        name: cherry-proxy
    spec:
      containers:
        - name: cherry-proxy
          image: "uherman/cherry-proxy:latest"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 5000
          env:
            - name: Auth0__Domain
              value: ${Auth0__Domain}
            - name: Auth0__ClientId
              value: ${Auth0__ClientId}
            - name: RedisOptions__ConnectionString
              value: ${RedisOptions__ConnectionString}
            - name: RedisOptions__DataProtectionKey
              value: ${RedisOptions__DataProtectionKey}
            - name: RedisOptions__DefaultDatabase
              value: "${RedisOptions__DefaultDatabase}"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: cherry-proxy
  name: cherry-proxy
spec:
  selector:
    app: cherry-proxy
  ports:
    - port: 5000
      name: http
      protocol: TCP
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cherry-proxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - cherry.null.care
        - www.cherry.null.care
      secretName: cherry-proxy-tls
  rules:
    - host: cherry.null.care
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cherry-proxy
                port:
                  number: 5000
    - host: www.cherry.null.care
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cherry-proxy
                port:
                  number: 5000